apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  creationTimestamp: '2026-03-23T23:30:11Z'
  generation: 4
  managedFields:
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2026-03-23T23:40:35Z'
  name: ci-cd-pipeline
  namespace: sn-labs-steintil70
  resourceVersion: '2714492301'
  uid: b82fd57a-8b05-4b5d-a762-b9878bba9475
spec:
  params:
    - default: 'image-registry.openshift-image-registry.svc:5000/sn-labs-steintil70/tekton-lab:latest'
      description: buildimage
      name: build-image
      type: string
  tasks:
    - name: cleanup
      taskRef:
        kind: Task
        name: cleanup
      workspaces:
        - name: source
          workspace: output
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/bird70/ci-cd-final-project'
        - name: revision
          value: ''
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:043080bff45cd129c0852b55a578c1a85e8911de80fadef22a21a034a1eccd56'
        - name: userHome
          value: /home/git
      runAfter:
        - cleanup
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: output
    - name: flake8
      params:
        - name: image
          value: 'python:3.9-slim'
        - name: path
          value: .
        - name: requirements_file
          value: requirements.txt
        - name: args
          value:
            - '--count'
            - '--max-complexity=10'
            - '--max-line-length=127'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: flake8
      workspaces:
        - name: source
          workspace: output
    - name: nose
      params:
        - name: args
          value: '-v'
      runAfter:
        - flake8
      taskRef:
        kind: Task
        name: nose
      workspaces:
        - name: source
          workspace: output
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.build-image)
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel8/buildah@sha256:aac6629389db17e99894c5bee0da01d4c8065d11d8c6f6e1602f9484290baa70'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - nose
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: output
    - name: openshift-client-deploy
      params:
        - name: SCRIPT
          value: oc deploy
        - name: VERSION
          value: latest
      runAfter:
        - buildah
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: output
